### ISSUE TITLE
Can I translate this to spanish?

### ISSUE THREAD

**Issue by pachamaltese** [datacamp/datacamp_facebook_live_intro_to_tidyverse#6]
Hi

I wanna translate this for my students. Can I?

**Comment by hugobowne** [comment]
Absolutely. All we require is that you attribute the content to DataCamp and Hugo Bowne-Anderson and that you make this clear and link to the original at the top of any relevant documents/repo/etc...

You can use the following:
"This is a translation of content created by DataCamp and Hugo Bowne-Anderson. You can find the original [here](https://github.com/datacamp/datacamp_facebook_live_intro_to_tidyverse)."

Also, do share your translation with us!

Close the issue when you are satisfied. Thanks.

**Comment by pachamaltese** [comment]
Thanks a lot!

**Comment by pachadotdev** [comment]
@hugobowne Hi. It's 100% translated to spanish here: https://github.com/visualizacion-uc/datacamp_facebook_live_intro_to_tidyverse

@jbkunst check this :)

**Comment by hugobowne** [comment]
awesome!
